spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: student-service
  cloud:
    config:
      profile: dev
      label: db-per-service
    aws:
      region:
        static: us-east-1
      stack:
        auto: false
      credentials:
        profile-name: s3