spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_exam
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  application:
    name: student-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      hibernate:
        SQL: debug
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: ${PORT:0}

cloud:
  aws:
    region:
      static: us-east-1
    stack:
        auto: false
    credentials:
      profile-name: s3